<a href="https://colab.research.google.com/github/suranimayur/End-to-End-Guide-on-Artificial-Neural-Network/blob/main/deep_learning_models_for_multi_output_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Deep-learning-models-for-multi-output-regression**

In [ ]:

# example of a multi-output regression problem
from sklearn.datasets import make_regression
# create dataset
X, y = make_regression(n_samples=1000, n_features=10, n_informative=5, n_targets=3, random_state=2)
# summarize shape
print(X.shape, y.shape)

(1000, 10) (1000, 3)


In [ ]:
print(X)
print(y)

[[-0.99859353  2.19284309 -0.42632569 ... -0.87625098 -0.99445578
  -0.3677487 ]
 [-0.88621913  0.58261383  0.13903253 ...  0.77270374  0.64154002
  -1.13040409]
 [-0.66436784  0.27447937 -1.60099657 ... -1.19078841 -0.0367227
  -0.54965583]
 ...
 [ 0.06468909  0.08012381 -1.3204591  ... -1.17063522  0.66082312
   1.08846103]
 [-0.99720001 -0.5371702  -0.01041399 ... -0.05874157  0.63516738
  -0.16871675]
 [ 0.05384091 -1.03029189 -1.13987039 ... -1.49285593  1.32674104
   1.8478841 ]]
[[-148.03723474  -80.63209848  -91.5736561 ]
 [ -82.27272654  -54.35420936 -114.40357938]
 [-160.04683144 -112.6928605   -78.47448648]
 ...
 [ -57.06470093   -3.65337026    5.37879727]
 [ -84.15214472  -28.85380227  -24.39982153]
 [ -28.32501715   35.58057957   93.02173732]]


In [ ]:
### Neural Network for Multi-Outputs

We will define a multilayer perceptron (MLP) model for the multi-output regression task defined in the previous section.



We will define a multilayer perceptron (MLP) model for the multi-output regression task defined in the previous section.

Each sample has 10 inputs and three outputs, therefore, the network requires an input layer that expects 10 inputs specified via the “input_dim” argument in the first hidden layer and three nodes in the output layer.

We will use the popular ReLU activation function in the hidden layer. The hidden layer has 20 nodes, which were chosen after some trial and error. We will fit the model using mean absolute error (MAE) loss and the Adam version of stochastic gradient descent.

In [ ]:
### The definition of the network for the multi-output regression task is listed below.



In [10]:
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

In [11]:
# define the model
model = Sequential()
model.add(Dense(20, input_dim=10, kernel_initializer='he_uniform', activation='relu'))
model.add(Dense(3))
model.compile(loss='mae', optimizer='adam')

You may want to adapt this model for your own multi-output regression task, therefore, we can create a function to define and return the model where the number of input and number of output variables are provided as arguments.

In [13]:

# get the model
def get_model(n_inputs, n_outputs):
 model = Sequential()
 model.add(Dense(20, input_dim=n_inputs, kernel_initializer='he_uniform', activation='relu'))
 model.add(Dense(n_outputs))
 model.compile(loss='mae', optimizer='adam')
 return model

#### Neural Network for Multi-Output Regression

```

```



Additionally, it is good practice to use k-fold cross-validation instead of train/test splits of a dataset to get an unbiased estimate of model performance when making predictions on new data. Again, only if there is not too much data and the process can be completed in a reasonable time.

Taking this into account, we will evaluate the MLP model on the multi-output regression task using repeated k-fold cross-validation with 10 folds and three repeats.

Each fold the model is defined, fit, and evaluated. The scores are collected and can be summarized by reporting the mean and standard deviation.

The evaluate_model() function below takes the dataset, evaluates the model, and returns a list of evaluation scores, in this case, MAE scores.

In [17]:

# evaluate a model using repeated k-fold cross-validation
def evaluate_model(X, y):
  results = list()
  n_inputs, n_outputs = X.shape[1], y.shape[1]
  # define evaluation procedure
  cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
  # enumerate folds
  for train_ix, test_ix in cv.split(X):
    # prepare data
    X_train, X_test = X[train_ix], X[test_ix]
    y_train, y_test = y[train_ix], y[test_ix]
  # define model
  model = get_model(n_inputs, n_outputs)
  # fit model
  model.fit(X_train, y_train, verbose=0, epochs=100)
  # evaluate model on test set
  mae = model.evaluate(X_test, y_test, verbose=0)
  # store result
  print('>%.3f' % mae)
  results.append(mae)
  return results

In [18]:
# mlp for multi-output regression
from numpy import mean
from numpy import std
from sklearn.datasets import make_regression
from sklearn.model_selection import RepeatedKFold
from keras.models import Sequential
from keras.layers import Dense
 

In [19]:
# get the dataset
def get_dataset():
  X, y = make_regression(n_samples=1000, n_features=10, n_informative=5, \
                         n_targets=3, random_state=2)
  return X, y

In [20]:
# get the model
def get_model(n_inputs, n_outputs):
  model = Sequential()
  model.add(Dense(20, input_dim=n_inputs, kernel_initializer='he_uniform', activation='relu'))
  model.add(Dense(n_outputs))
  model.compile(loss='mae', optimizer='adam')
  return model

In [21]:
# evaluate a model using repeated k-fold cross-validation
def evaluate_model(X, y):
  results = list()
  n_inputs, n_outputs = X.shape[1], y.shape[1]
  # define evaluation procedure
  cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
  # enumerate folds
  for train_ix, test_ix in cv.split(X):
  # prepare data
    X_train, X_test = X[train_ix], X[test_ix]
    y_train, y_test = y[train_ix], y[test_ix]
  # define model
  
  model = get_model(n_inputs, n_outputs)
  # fit model
  model.fit(X_train, y_train, verbose=0, epochs=100)
  # evaluate model on test set
  mae = model.evaluate(X_test, y_test, verbose=0)
  # store result
  print('>%.3f' % mae)
  results.append(mae)
  return results

In [22]:
 
# load dataset
X, y = get_dataset()
# evaluate model
results = evaluate_model(X, y)
# summarize performance
print('MAE: %.3f (%.3f)' % (mean(results), std(results)))

>6.820
MAE: 6.820 (0.000)
